version: '2'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres:5432/peh_db
      NODE_ENV: "production"
  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: peh_db
    ports:
      - "5434:5432"
